# Generated by Django 6.0.7 on 2026-07-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('layouts', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=512)),
                ('file_format', models.CharField(choices=[('xml', 'XML'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error'), ('review', 'Review')], default='pending', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_extraction_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_jobs', to='templates.pdfextractionconfig')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_jobs', to='catalogs.supplier')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_jobs', to='templates.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('layout_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_errors', to='layouts.layoutfield')),
                ('extraction_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='extraction.extractionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('extraction_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='extraction.extractionjob')),
                ('layout_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_results', to='layouts.layoutfield')),
            ],
            options={
                'ordering': ['extraction_job', 'layout_field__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['status', 'created_at'], name='extraction__status_f4e82b_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.UniqueConstraint(fields=('extraction_job', 'layout_field'), name='unique_layout_field_per_job'),
        ),
    ]
