# Generated by Django 6.0.7 on 2026-07-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_suppliercatalog_suppliercatalogcolumn_and_more'),
        ('extraction', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=512)),
                ('file_format', models.CharField(choices=[('xml', 'XML'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error'), ('review', 'Review')], default='pending', max_length=16)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='extractionjob',
            options={'ordering': ['row_number']},
        ),
        migrations.RemoveIndex(
            model_name='extractionjob',
            name='extraction__status_f4e82b_idx',
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='row_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='pdf_extraction_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_batches', to='templates.pdfextractionconfig'),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_batches', to='catalogs.supplier'),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='supplier_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_batches', to='catalogs.suppliercatalog'),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_batches', to='templates.template'),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='extraction_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='extraction.extractionbatch'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(fields=('extraction_batch', 'row_number'), name='unique_row_per_extraction_batch'),
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='pdf_extraction_config',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='template',
        ),
        migrations.AddIndex(
            model_name='extractionbatch',
            index=models.Index(fields=['status', 'created_at'], name='extraction__status_f4637e_idx'),
        ),
    ]
