# Generated by Django 6.0.7 on 2026-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_extractionbatch_alter_extractionjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
