# Generated by Django 6.0.8 on 2026-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_extractionbatch_processed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionbatch',
            name='pdf_extraction_config',
        ),
    ]
