# Generated by Django 5.2.17 on 2026-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_remove_extractionbatch_pdf_extraction_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='extractionerror',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
    ]
