# Generated by Django 6.0.7 on 2026-07-16 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g. Catálogo de Fracciones Suzuki', max_length=255)),
                ('pivot_field_name', models.CharField(help_text="Column name inside the catalog file used as lookup key, e.g. 'PART'", max_length=64)),
            ],
            options={
                'ordering': ['supplier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_name', models.CharField(help_text="Column name as it appears in the supplier's catalog file", max_length=128)),
            ],
            options={
                'ordering': ['supplier_catalog', 'source_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogColumnLayoutField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCatalogRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pivot_value', models.CharField(help_text='Lookup key value, e.g. the part number', max_length=128)),
                ('data', models.JSONField(default=dict, help_text='source_name -> raw value, per SupplierCatalogColumn')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='suppliercatalogitem',
            name='catalogs_su_supplie_98f507_idx',
        ),
        migrations.RemoveConstraint(
            model_name='suppliercatalogitem',
            name='unique_tariff_code_per_supplier',
        ),
        migrations.AddField(
            model_name='suppliercatalog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='catalogs.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumn',
            name='supplier_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='catalogs.suppliercatalog'),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_fields', to='catalogs.suppliercatalogcolumn'),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='layout_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='layouts.layoutfield'),
        ),
        migrations.AddField(
            model_name='suppliercatalogrow',
            name='supplier_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalogs.suppliercatalog'),
        ),
        migrations.RemoveField(
            model_name='suppliercatalogitem',
            name='supplier',
        ),
        migrations.AddConstraint(
            model_name='suppliercatalogcolumn',
            constraint=models.UniqueConstraint(fields=('supplier_catalog', 'source_name'), name='unique_column_per_catalog'),
        ),
        migrations.AddConstraint(
            model_name='suppliercatalogcolumnlayoutfield',
            constraint=models.UniqueConstraint(fields=('column', 'layout_field'), name='unique_layout_field_per_column'),
        ),
        migrations.AddIndex(
            model_name='suppliercatalogrow',
            index=models.Index(fields=['supplier_catalog', 'pivot_value'], name='catalogs_su_supplie_093255_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercatalogrow',
            constraint=models.UniqueConstraint(fields=('supplier_catalog', 'pivot_value'), name='unique_pivot_value_per_catalog'),
        ),
        migrations.DeleteModel(
            name='SupplierCatalogItem',
        ),
    ]
