# Generated by Django 6.0.7 on 2026-07-13 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_suppliercatalog_suppliercatalogcolumn_and_more'),
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercatalog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercatalog',
            name='pivot_layout_field',
            field=models.ForeignKey(default=1, help_text="Which layout_field, once extracted from the invoice, is used as the lookup value against this catalog's pivot_value", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='layouts.layoutfield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumn',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogrow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogrow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalog',
            name='pivot_field_name',
            field=models.CharField(help_text="Column name inside the catalog file used as lookup key, e.g. 'PART'", max_length=64),
        ),
    ]
