# Generated by Django 6.0.8 on 2026-08-18 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_suppliercatalog_suppliercatalogcolumn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
