# Generated by Django 6.0.8 on 2026-08-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_suppliercatalogcolumnlayoutfield_created_at_and_more'),
        ('templates', '0002_templatefield_header_occurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalogPivotMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pivot_template_field', models.ForeignKey(help_text='Campo extraído de la factura cuyo valor se usa para buscar la fila correspondiente en el catálogo.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='templates.templatefield')),
                ('supplier_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_mappings', to='catalogs.suppliercatalog')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_pivot_mappings', to='templates.template')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'supplier_catalog'), name='unique_pivot_mapping_per_template_catalog')],
            },
        ),
    ]
