# Generated by Django 6.0.8 on 2026-08-24 19:44

from django.db import migrations


def seed_umc(apps, schema_editor):
    Umc = apps.get_model("catalogs", "Umc")

    units = [
        ("1", "Kilo"),
        ("2", "Gramo"),
        ("3", "Metro lineal"),
        ("4", "Metro cuadrado"),
        ("5", "Metro cúbico"),
        ("6", "Pieza"),
        ("7", "Cabeza"),
        ("8", "Litro"),
        ("9", "Par"),
        ("10", "Kilowatt"),
        ("11", "Millar"),
        ("12", "Juego"),
        ("13", "Kilowatt/Hora"),
        ("14", "Tonelada"),
        ("15", "Barril"),
        ("16", "Gramo neto"),
        ("17", "Decenas"),
        ("18", "Cientos"),
        ("19", "Docenas"),
        ("20", "Caja"),
        ("21", "Botella"),
        ("22", "Carat"),
    ]

    Umc.objects.bulk_create(
        [
            Umc(code=code, description=description)
            for code, description in units
        ],
        ignore_conflicts=True,
    )


def reverse_seed_umc(apps, schema_editor):
    Umc = apps.get_model("catalogs", "Umc")
    Umc.objects.filter(
        code__in=[str(code) for code in range(1, 23)]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_suppliercatalogpivotmapping"),
    ]

    operations = [
        migrations.RunPython(seed_umc, reverse_seed_umc),
    ]