# Generated by Django 6.0.8 on 2026-08-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_seed_umc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
