from django.db import migrations


def seed_currencies(apps, schema_editor):
    Currency = apps.get_model("catalogs", "Currency")

    currencies = [
        ("XOF", "África Central"),
        ("ALL", "Albania"),
        ("EUR", "Alemania"),
        ("ANG", "Antillas Holandesas"),
        ("SAR", "Arabia Saudita"),
        ("DZD", "Argelia"),
        ("ARP", "Argentina"),
        ("AUD", "Australia"),
        ("EUR", "Austria"),
        ("BSD", "Bahamas"),
        ("BHD", "Bahréin"),
        ("BBD", "Barbados"),
        ("EUR", "Bélgica"),
        ("BZD", "Belice"),
        ("BMD", "Bermuda"),
        ("BOP", "Bolivia"),
        ("BRC", "Brasil"),
        ("BGL", "Bulgaria"),
        ("CAD", "Canadá"),
        ("CLP", "Chile"),
        ("CNY", "China"),
        ("CNE", "China"),
        ("EUR", "Chipre"),
        ("COP", "Colombia"),
        ("KPW", "Corea del Norte"),
        ("KRW", "Corea del Sur"),
        ("CRC", "Costa Rica"),
        ("CUP", "Cuba"),
        ("HRK", "Croacia (República de)"),
        ("DKK", "Dinamarca"),
        ("ECS", "Ecuador"),
        ("EGP", "Egipto"),
        ("SVC", "El Salvador"),
        ("AED", "Emiratos Árabes Unidos"),
        ("EUR", "Eslovenia"),
        ("EUR", "España"),
        ("EUR", "Estonia"),
        ("ETB", "Etiopía"),
        ("USD", "E.U.A."),
        ("RUR", "Fed. Rusa"),
        ("FJD", "Fidji"),
        ("PHP", "Filipinas"),
        ("EUR", "Finlandia"),
        ("EUR", "Francia"),
        ("GHC", "Ghana"),
        ("STG", "Gran Bretaña"),
        ("EUR", "Grecia"),
        ("GTO", "Guatemala"),
        ("GYD", "Guyana"),
        ("HTG", "Haití"),
        ("EUR", "Holanda"),
        ("HNL", "Honduras"),
        ("HKD", "Hong Kong"),
        ("HUF", "Hungría"),
        ("INR", "India"),
        ("IDR", "Indonesia"),
        ("IQD", "Irak"),
        ("IRR", "Irán"),
        ("EUR", "Irlanda"),
        ("ISK", "Islandia"),
        ("ILS", "Israel"),
        ("EUR", "Italia"),
        ("JMD", "Jamaica"),
        ("JPY", "Japón"),
        ("JOD", "Jordania"),
        ("KES", "Kenya"),
        ("KWD", "Kuwait"),
        ("EUR", "Letonia"),
        ("LBP", "Libano"),
        ("LYD", "Libia"),
        ("LTT", "Lituania"),
        ("EUR", "Luxemburgo"),
        ("MYR", "Malasia"),
        ("EUR", "Malta"),
        ("MAD", "Marruecos"),
        ("MXP", "México"),
        ("EUR", "Montenegro"),
        ("NIC", "Nicaragua"),
        ("NGN", "Nigeria (Fed)"),
        ("NOK", "Noruega"),
        ("NZD", "Nueva Zelanda"),
        ("PKR", "Pakistán"),
        ("ILS", "Palestina"),
        ("PAB", "Panamá"),
        ("PYG", "Paraguay"),
        ("PES", "Perú"),
        ("PLZ", "Polonia"),
        ("EUR", "Portugal"),
        ("USD", "Puerto Rico"),
        ("CSK", "República Checa"),
        ("ZRZ", "República Democrática del Congo"),
        ("RSD", "República de Serbia"),
    ]

    Currency.objects.bulk_create(
        [
            Currency(code=code, country=country)
            for code, country in currencies
        ]
    )


def reverse_seed_currencies(apps, schema_editor):
    Currency = apps.get_model("catalogs", "Currency")

    Currency.objects.filter(
        country__in=[
            "África Central",
            "Albania",
            "Alemania",
            "Antillas Holandesas",
            "Arabia Saudita",
            "Argelia",
            "Argentina",
            "Australia",
            "Austria",
            "Bahamas",
            "Bahréin",
            "Barbados",
            "Bélgica",
            "Belice",
            "Bermuda",
            "Bolivia",
            "Brasil",
            "Bulgaria",
            "Canadá",
            "Chile",
            "China",
            "Chipre",
            "Colombia",
            "Corea del Norte",
            "Corea del Sur",
            "Costa Rica",
            "Cuba",
            "Croacia (República de)",
            "Dinamarca",
            "Ecuador",
            "Egipto",
            "El Salvador",
            "Emiratos Árabes Unidos",
            "Eslovenia",
            "España",
            "Estonia",
            "Etiopía",
            "E.U.A.",
            "Fed. Rusa",
            "Fidji",
            "Filipinas",
            "Finlandia",
            "Francia",
            "Ghana",
            "Gran Bretaña",
            "Grecia",
            "Guatemala",
            "Guyana",
            "Haití",
            "Holanda",
            "Honduras",
            "Hong Kong",
            "Hungría",
            "India",
            "Indonesia",
            "Irak",
            "Irán",
            "Irlanda",
            "Islandia",
            "Israel",
            "Italia",
            "Jamaica",
            "Japón",
            "Jordania",
            "Kenya",
            "Kuwait",
            "Letonia",
            "Libano",
            "Libia",
            "Lituania",
            "Luxemburgo",
            "Malasia",
            "Malta",
            "Marruecos",
            "México",
            "Montenegro",
            "Nicaragua",
            "Nigeria (Fed)",
            "Noruega",
            "Nueva Zelanda",
            "Pakistán",
            "Palestina",
            "Panamá",
            "Paraguay",
            "Perú",
            "Polonia",
            "Portugal",
            "Puerto Rico",
            "República Checa",
            "República Democrática del Congo",
            "República de Serbia",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0006_alter_currency_code"),
    ]

    operations = [
        migrations.RunPython(
            seed_currencies,
            reverse_seed_currencies,
        ),
    ]