# Generated by Django 5.2.17 on 2026-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_seed_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalogcolumn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalogcolumnlayoutfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalogpivotmapping',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='suppliercatalogrow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='umc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
    ]
