# Generated by Django 6.0.8 on 2026-08-14 22:40

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='layoutfield',
            name='unique_sort_order_per_layout',
        ),
        migrations.AddConstraint(
            model_name='layoutfield',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('layout', 'sort_order'), name='unique_sort_order_per_layout'),
        ),
    ]
