# Generated by Django 6.0.8 on 2026-08-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_remove_layoutfield_unique_sort_order_per_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutfield',
            name='system_field_key',
            field=models.CharField(blank=True, choices=[('', 'No es campo de sistema'), ('supplier_code', 'Código del proveedor')], default='', help_text='Si se define, este campo se resuelve automáticamente por el sistema en vez de mapearse desde un TemplateField.', max_length=64),
        ),
    ]
