# Generated by Django 5.2.17 on 2026-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_layoutfield_system_field_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizationrule',
            name='rule_type',
            field=models.CharField(choices=[('date_format', 'Date format'), ('value_map', 'Value map'), ('regex_replace', 'Regex replace'), ('trim', 'Trim'), ('uppercase', 'Uppercase'), ('spanish_date', 'Fecha en español (ej. 22 de julio de 2026)')], max_length=32),
        ),
    ]
