# Generated by Django 5.2.17 on 2026-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0004_alter_normalizationrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='layout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_name'),
        ),
    ]
