# Generated by Django 6.0.7 on 2026-07-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfExtractionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('base_prompt', models.TextField()),
                ('hints', models.TextField(blank=True, help_text='Supplier-specific instructions such as currency, field locations, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_extraction_configs', to='layouts.layout')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_extraction_configs', to='catalogs.supplier')),
            ],
            options={
                'ordering': ['supplier', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('xml', 'XML'), ('xlsx', 'XLSX')], max_length=8)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='layouts.layout')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='catalogs.supplier')),
            ],
            options={
                'ordering': ['supplier', 'layout', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_field', models.CharField(max_length=255)),
                ('extraction_type', models.CharField(choices=[('header_name', 'Header name'), ('xpath', 'XPath')], max_length=16)),
                ('worksheet', models.CharField(blank=True, help_text='XLSX only', max_length=128)),
                ('layout_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_fields', to='layouts.layoutfield')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.template')),
            ],
            options={
                'ordering': ['template', 'layout_field__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(help_text='Execution order when multiple rules are chained')),
                ('normalization_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_fields', to='layouts.normalizationrule')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='templates.templatefield')),
            ],
            options={
                'ordering': ['template_field', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('supplier', 'layout', 'document_type'), name='unique_active_template_per_supplier_layout_format'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template', 'layout_field'), name='unique_layout_field_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templatefieldrule',
            constraint=models.UniqueConstraint(fields=('template_field', 'normalization_rule'), name='unique_rule_per_template_field'),
        ),
    ]
