# Generated by Django 6.0.7 on 2026-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='header_occurrence',
            field=models.PositiveIntegerField(default=1, help_text='Si el encabezado se repite en el excel, indica qué ocurrencia corresponde a este campo (1 = primera columna con ese nombre, 2 = segunda, etc.). Para encabezados únicos, deja 1.'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template', 'source_field', 'header_occurrence'), name='unique_source_field_occurrence_per_template'),
        ),
    ]
