# Generated by Django 6.0.8 on 2026-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_layoutfield_system_field_key'),
        ('templates', '0002_templatefield_header_occurrence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='templatefield',
            name='unique_source_field_occurrence_per_template',
        ),
        migrations.AddField(
            model_name='template',
            name='pdf_extraction_mode',
            field=models.CharField(blank=True, choices=[('text_only', 'Solo texto'), ('text_and_tables', 'Texto y tablas')], help_text="Solo aplica cuando document_type='pdf'. Define si pdfplumber extrae solo texto plano o texto + tablas detectadas.", max_length=20),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='anchor_position',
            field=models.CharField(blank=True, choices=[('after', 'Después del ancla'), ('before', 'Antes del ancla'), ('same_line', 'Misma línea que el ancla'), ('below', 'Debajo del ancla')], help_text='LLM only. Posición del valor respecto a anchor_text.', max_length=16),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='anchor_text',
            field=models.CharField(blank=True, help_text="LLM only. Texto literal presente en el documento que sirve de referencia para ubicar el valor (ej. 'Fecha de factura:').", max_length=255),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='expected_data_type',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('date', 'Fecha'), ('amount', 'Monto'), ('number', 'Número')], help_text='LLM only. Hint del tipo de valor esperado (no convierte, solo guía al LLM)', max_length=16),
        ),
        migrations.AlterField(
            model_name='template',
            name='document_type',
            field=models.CharField(choices=[('xml', 'XML'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=8),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='extraction_type',
            field=models.CharField(choices=[('header_name', 'Header name'), ('xpath', 'XPath'), ('llm_text', 'LLM (texto libre)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='source_field',
            field=models.CharField(blank=True, help_text='Requerido para header_name (nombre de columna) y xpath. No aplica para llm_text (usa anchor_text en su lugar).', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('extraction_type', 'header_name')), fields=('template', 'source_field', 'header_occurrence'), name='unique_source_field_occurrence_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('extraction_type', 'xpath')), fields=('template', 'source_field'), name='unique_xpath_per_template'),
        ),
    ]
