# Generated by Django 6.0.8 on 2026-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_remove_extractionbatch_pdf_extraction_config'),
        ('templates', '0003_remove_templatefield_unique_source_field_occurrence_per_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfExtractionConfig',
        ),
    ]
