# Generated by Django 6.0.8 on 2026-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_delete_pdfextractionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='line_pattern_hint',
            field=models.TextField(blank=True, help_text="PDF only. Descripción del patrón posicional de una línea de renglón cuando NO hay tabla detectada ni encabezado de columna identificable en el texto. Ej: 'Cada línea trae cantidad, precio y descripción, en ese orden, separados por espacios. Ejemplo: 4  10.00  Manzanas'. Solo tiene sentido si existe al menos un TemplateField con scope='line_item'."),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='block_end_anchor',
            field=models.CharField(blank=True, help_text="LLM + scope='line_item'. Texto que marca el fin de la zona de renglones (ej. 'Subtotal'). Si se deja vacío, el pipeline usa una lista genérica de palabras de corte definida a nivel de sistema (Subtotal, Total, IVA, etc.).", max_length=255),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='block_start_anchor',
            field=models.CharField(blank=True, help_text="LLM + scope='line_item'. Texto que marca el inicio de la zona de renglones (ej. encabezado de columna 'Cantidad Precio Descripción', si existe). Opcional: si no hay texto estable de inicio, se puede dejar vacío y usar solo block_end_anchor.", max_length=255),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='scope',
            field=models.CharField(choices=[('header', 'Encabezado (valor único por documento)'), ('line_item', 'Renglón de partida (se repite por fila)')], default='header', help_text="LLM only. 'header' = valor único en el documento. 'line_item' = se repite una vez por cada renglón de una tabla de partidas.", max_length=10),
        ),
        migrations.AlterField(
            model_name='template',
            name='pdf_extraction_mode',
            field=models.CharField(blank=True, choices=[('text_only', 'Solo texto'), ('text_and_tables', 'Texto y tablas')], help_text="Solo aplica cuando document_type='pdf'. Define si pdfplumber extrae solo texto plano o texto + tablas detectadas. Obligatorio 'text_and_tables' si el template tiene campos scope='line_item'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='anchor_position',
            field=models.CharField(blank=True, choices=[('after', 'Después del ancla'), ('before', 'Antes del ancla'), ('below', 'Debajo del ancla')], help_text="LLM + scope='header'. Posición del valor respecto a anchor_text.", max_length=16),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='anchor_text',
            field=models.CharField(blank=True, help_text="LLM + scope='header'. Texto literal presente en el documento que sirve de referencia para ubicar el valor (ej. 'Fecha de factura:').", max_length=255),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='expected_data_type',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('date', 'Fecha'), ('amount', 'Monto'), ('number', 'Número')], help_text='LLM only. Hint del tipo de valor esperado (no convierte, solo guía al LLM; la conversión real la hace NormalizationRule).', max_length=16),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='source_field',
            field=models.CharField(blank=True, help_text='Requerido para header_name (nombre de columna) y xpath. No aplica para llm_text.', max_length=255),
        ),
    ]
