# Generated by Django 6.0.8 on 2026-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_template_line_pattern_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
