# Generated by Django 5.2.17 on 2026-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='templatefieldrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
    ]
